vich_uploader:
    db_driver: orm

    mappings:
        category_image:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        book_image:
            uri_prefix: /images/books
            upload_destination: '%kernel.project_dir%/public/images/books'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    metadata:
        type: attribute
