
http://localhost:8000/api/books?published=true


###

http://localhost:8000/api/books/1

###

http://localhost:8000/api/categories

### 
https://localhost:8000/api/categories

###
POST https://localhost:8000/checkout HTTP/1.1 
content-type: application/json

{
   "first":"test"
}