
http://localhost:8000/api/books?published=true


###

http://localhost:8000/api/books/1

###

http://localhost:8000/api/categories

### 
https://localhost:8000/api/categories

###
POST https://localhost:8000/checkout HTTP/1.1 
content-type: application/json
X-Requested-With: XMLHttpRequest

{
   "first":"test"   
}

###

POST https://localhost:8000/api/orders 
content-type: application/json
X-Requested-With: XMLHttpRequest

{
"shipAddress": "26 rue",
"shipCity": "city",
"shipZipCode": "80000",
"coef": "0.00",
"billAddress": "26 rue",
"billZipCode": "80000",
"billCity": "city",
"userClient": "2",
"payMethod": "Bank Transfer"
}